version: 2
jobs:
  xenial-gcc-5.3:
    docker:
      - image: ubuntu:xenial
    environment:
      KDIR: /lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o | sed -r 's/(.*)\./\1-/')-generic/build
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y gcc make linux-headers-generic
      - run:
          name: Build
          command: |
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name: Install
          command: |
            make install

  bionic-gcc-7.4:
    docker:
      - image: ubuntu:bionic
    environment:
      KDIR: /lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o | sed -r 's/(.*)\./\1-/')-generic/build
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y gcc make linux-headers-generic
      - run:
          name: Build
          command: |
            make
      - run:
          name: Test
          command: |
            make check
      - run:
          name: Install
          command: |
            make install

workflows:
  version: 2
  build:
    jobs:
      - xenial-gcc-5.3
      - bionic-gcc-7.4
