version: 2
jobs:
  xenial-gcc-5.3:
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y gcc make linux-headers-generic
      - run:
          name: Build
          command: |
            make KDIR=/lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o)/build
      - run:
          name: Test
          command: |
            make check KDIR=/lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o)/build
      - run:
          name: Install
          command: |
            make install KDIR=/lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o)/build

  bionic-gcc-7.4:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt update -qq && apt install -y gcc make linux-headers-generic
      - run:
          name: Build
          command: |
            make KDIR=/lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o)/build
      - run:
          name: Test
          command: |
            make check KDIR=/lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o)/build
      - run:
          name: Install
          command: |
            make install KDIR=/lib/modules/$(dpkg -s linux-headers-generic | egrep '[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*\.[0-9]+*$' -o)/build

workflows:
  version: 2
  build:
    jobs:
      - xenial-gcc-5.3
      - bionic-gcc-7.4
